import sys
import pandas as pd
from src.exception import CustomException
from src.utils import load_object


class PredictPipeline:
    """
    Pipeline class responsible for loading the trained model and preprocessor,
    transforming incoming feature data, and generating predictions.
    """

    def __init__(self):
        pass

    def predict(self, features):
        """
        Generates predictions using the saved model and preprocessor.

        Parameters
        ----------
        features : pandas.DataFrame
            Raw input data that needs to be transformed before prediction.

        Returns
        -------
        numpy.ndarray
            An array of prediction values generated by the trained model.

        Raises
        ------
        CustomException
            Raised for any errors encountered during loading or prediction.
        """
        try:
            # Paths to the serialized model and preprocessor files
            model_path = 'artifacts\\model.pkl'
            preprocessor_path = 'artifacts\\preprocessor.pkl'

            # Load the saved model and preprocessing pipeline
            model = load_object(file_path=model_path)
            preprocessor = load_object(file_path=preprocessor_path)

            # Transform input features using the preprocessor
            data_scaled = preprocessor.transform(features)

            # Generate predictions
            preds = model.predict(data_scaled)
            return preds

        except Exception as e:
            # Wrap any exception with custom error handling
            raise CustomException(e, sys)


class CustomData:
    """
    A helper class to structure user input into a DataFrame format compatible
    with the machine learning model's expected feature schema.
    """

    def __init__(
        self,
        gender: str,
        race_ethnicity: str,
        parental_level_of_education,
        lunch: str,
        test_preparation_course: str,
        reading_score: int,
        writing_score: int
    ):
        """
        Initializes the CustomData object with the feature values.

        Parameters
        ----------
        gender : str
            Gender of the student.
        race_ethnicity : str
            Race/ethnicity classification.
        parental_level_of_education : str
            Highest education level attained by parents.
        lunch : str
            Type of lunch (e.g., 'standard', 'free/reduced').
        test_preparation_course : str
            Completion status of test preparation course.
        reading_score : int
            Student's reading score.
        writing_score : int
            Student's writing score.
        """
        self.gender = gender
        self.race_ethnicity = race_ethnicity
        self.parental_level_of_education = parental_level_of_education
        self.lunch = lunch
        self.test_preparation_course = test_preparation_course
        self.reading_score = reading_score
        self.writing_score = writing_score

    def get_data_as_data_frame(self):
        """
        Converts the initialized custom data attributes into a pandas DataFrame.

        Returns
        -------
        pandas.DataFrame
            A DataFrame containing a single row of user-provided feature values.

        Raises
        ------
        CustomException
            Raised if DataFrame creation fails.
        """
        try:
            # Construct a dictionary of feature names and values
            custom_data_input_dict = {
                "gender": [self.gender],
                "race_ethnicity": [self.race_ethnicity],
                "parental_level_of_education": [self.parental_level_of_education],
                "lunch": [self.lunch],
                "test_preparation_course": [self.test_preparation_course],
                "reading_score": [self.reading_score],
                "writing_score": [self.writing_score]
            }

            # Return the features as a DataFrame
            return pd.DataFrame(custom_data_input_dict)

        except Exception as e:
            # Handle and forward any error
            raise CustomException(e, sys)
